data_ingestion:
 bucket_name : "my-vertexai-pipeline-bucket"
 bucket_file_name : "Hotel_Reservations.csv"
 train_ratio : 0.8


data_processing:
 categorical_columns:
  - type_of_meal_plan
  - room_type_reserved
  - market_segment_type
  - booking_status
  

 numerical_columns:
  - no_of_adults
  - no_of_children
  - no_of_special_requests
  - lead_time
  - arrival_year
  - no_of_weekend_nights
  - no_of_week_nights
  - required_car_parking_space
  - arrival_month
  - arrival_date
  - repeated_guest
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room

 skew_threshold: 5

 no_of_features: 10

  
  
 
